name: CAT-DM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy<2.0  
    - torch~=2.7.0
    - torch-fidelity
    - torchmetrics
    - torchvision
    - pytorch-lightning
    - transformers      
    - albumentations
    - diffusers
    - bezier
    - opencv-python
    - pudb
    - invisible-watermark
    - imageio
    - imageio-ffmpeg
    - omegaconf
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops
    - kornia
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .